/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment_1;

import java.util.*;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.*;
public class Tester {
    @Test
    void nabongu(){
        Map<String, String> expectedCommands=new HashMap<>();
        expectedCommands.put("findMovies","SELECT a, b, c FROM my_table WHERE x=${propX} AND y=${propY};");
        expectedCommands.put("addMovie","INSERT INTO my_table(x, y, x) VALUES(${propX}, ${propY}, ${propZ});");
        assertEquals(expectedCommands, XmlDomParser.read().get(1));
        Sql_connection ex=new Sql_connection();
        ex.main(null);
    }
}

